In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
DATA_DIR = '/home/sha/work/data/'
MASTER_FILE_NAME = 'Master_List.xlsx'
TAX_FILE_NAME = 'taxo_data_1.csv'
MASTER_TAX_FILE_NAME = 'master_tax_1.csv'

In [3]:
master_file = os.path.join(DATA_DIR, MASTER_FILE_NAME)
tax_file = os.path.join(DATA_DIR, TAX_FILE_NAME)

In [5]:
master = pd.read_excel(master_file)
tax = pd.read_csv(tax_file)

In [6]:
master.drop(columns=['Sample_body_site', 'Type', 'urls'], inplace=True)
unique_master = master.drop_duplicates(
    subset=['Subject_ID', 'Visit_number', 'Visit_ID', 'Age', 'Sex', 'Diagnosis', 'Race']
)
# genus_abundances = tax.loc[:,["Visit_name", 'Genus', 'Metaphlan2_Analysis']]
# genus_abundances.reset_index(inplace=True)
# genus_abundances.rename(columns={'index': 'idx', 'Visit_name': 'Visit_ID'}, inplace=True)
# genus = genus_abundances.pivot(index='idx', columns='Genus', values='Metaphlan2_Analysis')
# genus['Visit_ID'] = genus_abundances['Visit_ID']

In [7]:
unique_master

      Subject_ID  Visit_number  Visit_ID  Age     Sex Diagnosis   Race
0           2008            23  MSM5LLDE   30  Female        CD  White
4           2008             6  MSM5LLDM   30  Female        CD  White
11          2008            28  MSM6J2LB   30  Female        CD  White
18          2008            11  MSM5LLDU   30  Female        CD  White
25          2008            22  MSM5LLDC   30  Female        CD  White
...          ...           ...       ...  ...     ...       ...    ...
7501        3022            19  CSM7KOOH   69    Male    nonIBD  White
7508        3022             4  CSM67UH7   69    Male    nonIBD  White
7512        3022            22  CSM7KOON   69    Male    nonIBD  White
7516        3022            25  CSM7KOOR   69    Male    nonIBD  White
7522        3022             8  CSM79HGZ   69    Male    nonIBD  White

[1339 rows x 7 columns]

In [8]:
# master.drop(columns=['Sample_body_site', 'Type', 'urls'], inplace=True)
# unique_master = master.drop_duplicates(
#     subset=['Subject_ID', 'Visit_number', 'Visit_ID', 'Age', 'Sex', 'Diagnosis', 'Race']
# )
genus_abundances = tax.loc[:,["Visit_name", 'Genus', 'Metaphlan2_Analysis']]
genus_abundances.reset_index(inplace=True)
genus_abundances.rename(columns={'index': 'idx', 'Visit_name': 'Visit_ID'}, inplace=True)

In [9]:
genus_abundances

,idx,Visit_ID,Genus,Metaphlan2_Analysis
0,0,HSM7J4ON,g__Bacteroides,84.78718
1,1,HSM7J4ON,g__Faecalibacterium,5.97392
2,2,HSM7J4ON,g__Parabacteroides,3.60682
3,3,HSM7J4ON,g__Dialister,2.59404
4,4,HSM7J4ON,g__Roseburia,0.88994
...,...,...,...,...
38270,38270,CSM7KOUN,g__Holdemania,0.02449
38271,38271,CSM7KOUN,g__Propionibacteriaceae_unclassified,0.02427
38272,38272,CSM7KOUN,g__C2likevirus,0.02108
38273,38273,CSM7KOUN,g__Pseudoflavonifractor,0.00595
38274,38274,CSM7KOUN,g__Ruminococcus,0.00557

In [10]:
genus = genus_abundances.pivot(index='idx', columns='Genus', values='Metaphlan2_Analysis')
genus['Visit_ID'] = genus_abundances['Visit_ID']

In [11]:
genus

Genus,g__Abiotrophia,g__Acidaminococcaceae_unclassified,g__Acidaminococcus,g__Acinetobacter,g__Actinobacillus,g__Actinobaculum,g__Actinomyces,g__Adlercreutzia,g__Aerococcus,g__Aggregatibacter,...,g__Treponema,g__Tunalikevirus,g__Turicibacter,g__Ureaplasma,g__Varibaculum,g__Veillonella,g__Weissella,g__Wohlfahrtiimonas,g__Yersinia,Visit_ID
idx,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSM7J4ON
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSM7J4ON
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSM7J4ON
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSM7J4ON
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSM7J4ON
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CSM7KOUN
38271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CSM7KOUN
38272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CSM7KOUN
38273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CSM7KOUN
38274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CSM7KOUN

In [12]:
group_genus = genus.groupby('Visit_ID').sum()

In [13]:
group_genus

Genus,g__Abiotrophia,g__Acidaminococcaceae_unclassified,g__Acidaminococcus,g__Acinetobacter,g__Actinobacillus,g__Actinobaculum,g__Actinomyces,g__Adlercreutzia,g__Aerococcus,g__Aggregatibacter,...,g__Tetragenococcus,g__Treponema,g__Tunalikevirus,g__Turicibacter,g__Ureaplasma,g__Varibaculum,g__Veillonella,g__Weissella,g__Wohlfahrtiimonas,g__Yersinia
Visit_ID,,,,,,,,,,,,,,,,,,,,,
CSM5FZ4M,0.0,0.24017,2.87905,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
CSM5MCUO,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00630,0.0,0.0,0.0
CSM5MCVL,0.0,0.00000,0.96519,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
CSM5MCVN,0.0,0.65498,12.25678,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
CSM5MCW6,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00129,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PSMB4MBS,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
PSMB4MC1,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.16083,0.0,0.0,0.0
PSMB4MC3,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.10419,0.0,0.0,0.0
PSMB4MC5,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.08066,0.0,0.0,0.0
PSMB4MC7,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.01075,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.13864,0.0,0.0,0.0

In [14]:
unique_master['Visit_ID'].value_counts()

Visit_ID
MSM5LLDE    1
MSM79HF9    1
MSM9VZLT    1
MSM79HAT    1
MSM9VZLV    1
           ..
MSM9VZKE    1
MSMA26BR    1
MSM9VZFR    1
MSM9VZKC    1
CSM79HGZ    1
Name: count, Length: 1339, dtype: int64

In [15]:
tax['Visit_name'].value_counts()

Visit_name
MSM79HF9    90
CSM79HPA    75
MSM9VZNH    74
HSM67VEM    63
HSM5MD6A    62
            ..
HSM7J4LH     2
HSMA33N4     2
PSM6XBTD     1
CSM7KOOR     1
PSM7J1BH     1
Name: count, Length: 1313, dtype: int64

In [16]:
result = pd.merge(unique_master, group_genus, on='Visit_ID')
result = result.fillna(0.0)
result.to_csv(os.path.join(DATA_DIR, MASTER_TAX_FILE_NAME))

In [17]:
result.shape

(1313, 196)

In [18]:
unique_master['Visit_number'].value_counts().sort_index()

Visit_number
4     23
5     61
6     65
7     51
8     78
9     79
11    38
12    57
13    79
14    43
15    50
16    56
18    85
19    72
20    47
21    48
22    58
23    76
25    82
26    61
27    39
28    30
29    30
30    31
Name: count, dtype: int64